-- Optional lookup tables for ticket enrichment (KMP matcher).
-- This keeps the existing tickets schema intact; enrichment writes to tickets.tags.

create table if not exists public.pharmacies (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  chain_name text not null,
  address text not null,
  city text not null,
  state text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_pharmacies_org_chain_state
  on public.pharmacies (organization_id, chain_name, state);

create table if not exists public.medication_search_terms (
  id bigint generated by default as identity primary key,
  search_term text not null,
  canonical_id bigint not null,
  created_at timestamptz not null default now(),
  unique (search_term)
);

create index if not exists idx_medication_search_terms_search_term
  on public.medication_search_terms (search_term);
